### ISSUE TITLE
Fix the token refresh in the Python client (+ associated flaky tests)

### ISSUE THREAD

**Issue by alexwlchan** [wellcomecollection/storage-service#983]
We sometimes see the "deploy stage" task fail in CI, because it takes over an hour to send a bag through the staging storage service, e.g. https://buildkite.com/wellcomecollection/storage-service-deploy-stage/builds/46

The exact error we see is:

```
Traceback (most recent call last):
  | File ".buildkite/scripts/send_and_wait_for_test_bag.py", line 59, in <module>
  | current_ingest = client.get_ingest_from_location(ingest_url)
  | File "/var/lib/buildkite-agent/.local/lib/python3.7/site-packages/wellcome_storage_service/__init__.py", line 54, in get_ingest_from_location
  | status_code, body = self._http_get(ingest_url)
  | File "/var/lib/buildkite-agent/.local/lib/python3.7/site-packages/wellcome_storage_service/__init__.py", line 174, in wrapper
  | return f(self, *args, **kwargs)
  | File "/var/lib/buildkite-agent/.local/lib/python3.7/site-packages/wellcome_storage_service/__init__.py", line 205, in _http_get
  | return super(RequestsOAuthStorageServiceClient, self)._http_get(url)
  | File "/var/lib/buildkite-agent/.local/lib/python3.7/site-packages/wellcome_storage_service/__init__.py", line 153, in _http_get
  | resp = self.sess.get(url)
  | File "/var/lib/buildkite-agent/.local/lib/python3.7/site-packages/requests/sessions.py", line 542, in get
  | return self.request('GET', url, **kwargs)
  | File "/var/lib/buildkite-agent/.local/lib/python3.7/site-packages/requests_oauthlib/oauth2_session.py", line 478, in request
  | url, http_method=method, body=data, headers=headers
  | File "/var/lib/buildkite-agent/.local/lib/python3.7/site-packages/oauthlib/oauth2/rfc6749/clients/base.py", line 198, in add_token
  | raise TokenExpiredError()
  | oauthlib.oauth2.rfc6749.errors.TokenExpiredError: (token_expired)
```

The Python client *should* be refreshing the token when it expires, but apparently it isn't.

Fixing this would make these tests more reliable.

**Comment by alexwlchan** [comment]
Nooooo still broken: https://buildkite.com/wellcomecollection/storage-service-deploy-stage/builds/82#0183403b-b754-4ae7-a85b-dc7444f4c846

**Comment by alexwlchan** [comment]
Yeah so it turns out this was nothing to do with token refresh, and everything to do with a line in the tests that said 'fail this after an hour". Should be fixed now. 🤦‍♀️
